version: "3"

services:
  app:
    build:
      context: .
    environment:
      - MONGO_URL=mongodb://mongo:27017/blogging
    depends_on:
      - mongo
    networks:
      - app-network
    ports:
      - "3000:3000"

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

volumes:
  mongo-data:

networks:
  app-network:
