name: CI Pipeline

# Define when the pipeline should run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: --health-cmd "echo 'db.runCommand({ connectionStatus: 1 })' | mongo localhost:27017/test --quiet" --health-interval=10s --health-timeout=5s --health-retries=5

      app:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - 3000:3000
        env:
          MONGO_URL: mongodb://mongo:27017/blogging
        options: --health-cmd "curl --fail http://localhost:3000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./app

    - name: Run tests
      run: npm run test
      working-directory: ./app
